### ISSUE TITLE
Send SigLens internal metrics to itself.

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#123]
Currently we use prometheus to scrape internal metrics at regular intervals. These are stored in prometheus time series database. OTEL collector is configured to forward these metrics from prometheus to siglens metrics ingest endpoint. This allows us to use these metrics in our self monitoring /default dashboards.
We want to add a cron job to send siglens metrics to itself without using prometheus/ OTEL collector.

Siglens instrumentation package collects internal metrics pkg/instrumentation/metrics.go
we use https://github.com/prometheus/client_golang

Prometheus set up:
- Download prometheus https://prometheus.io/download/
- Once Prometheus is started with default settings, its web UI will be listening at port 9090:
- Promentheus will scrape metrics from local siglens instance. Configure that using /prometheus/prometheus.yml

```
  scrape_interval:     15s
  evaluation_interval: 15s

- job_name:       'siglens'
    static_configs:
      - targets: ['localhost:2222']
        labels:
          group: 'production'
```

OTEL collector set up
- get the MacOS release using: `curl --proto '=https' --tlsv1.2 -fOL https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.80.0/otelcol_0.80.0_darwin_amd64.tar.gz`
- They are packaged as gzipped tarballs (.tar.gz) and will need to be unpacked with a tool that supports this compression format: `tar -xvf otelcol_0.80.0_darwin_amd64.tar.gz`
- Every Collector release includes an otelcol executable that you can run after unpacking.
- Create a config.yaml file which will contain the configurations for the otelCol
- Run otelCol using: `./otelCol --config config.yaml`

The config file used: 
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'siglens'
          scrape_interval: 60s
          static_configs:
            - targets: ['localhost:2222']

processors:
  batch:

exporters:
  logging:
    loglevel: debug

  prometheusremotewrite:
    endpoint: 'http://localhost:8081/promql/api/v1/write'
    headers:
      Authorization: 'Bearer YOUR_TOKEN_HERE'  # Optional: Add any necessary headers

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
